steps:
  - id: lint-yaml
    name: 'gcr.io/$PROJECT_ID/cloudbuilders/yamllint:1.20.0'
    args: ["-d", "relaxed", "."]
    waitFor: ['-']

  - id: lint-docker
    name: 'gcr.io/$PROJECT_ID/cloudbuilders/hadolint:1.18.0'
    args:
      - Dockerfile
    waitFor: ['-']

  - id: npm-lockfile
    name: node:18
    secretEnv: ['NPM_TOKEN']
    entrypoint: npm
    args: ['i', '--quiet', '--package-lock-only']

  - id: npm-audit
    name: 'gcr.io/$PROJECT_ID/cloudbuilders/audit-exclude'
    secretEnv: ['NPM_TOKEN']
    entrypoint: '/bin/ash'
    args:
      - -c
      - npm audit --production --json | audit-exclude

  - id: docker-compose
    name: 'docker/compose:1.29.2'
    args: ['up', '-d']
    waitFor: ['npm-audit', 'lint-yaml', 'lint-docker']

  - id: npm-ci
    name: node:18-alpine
    secretEnv: ["NPM_TOKEN"]
    entrypoint: npm
    args: [ 'ci', '--quiet' ]
    waitFor: ['npm-lockfile']

  - id: test-e2e
    name: node:18-alpine
    secretEnv: ["NPM_TOKEN"]
    entrypoint: npm
    args: [ 'run', 'test' ]
    env:
    - 'NODE_ENV=test'
    - 'RABBIT_URL=amqp://admin:admin@rabbitmq:5672/db'
    waitFor: ['npm-ci', 'docker-compose']
    allowFailure: true

  - id: docker-compose-logs
    name: 'docker/compose:1.29.2'
    args: [ 'logs', 'rabbitmq' ]
    waitFor: [ 'test-e2e' ]

#  - id: npm-publish
#    name: 'gcr.io/$PROJECT_ID/cloudbuilders/npm:6.13.4'
#    secretEnv: ['NPM_TOKEN']
#    env:
#      - 'TAG_NAME=$TAG_NAME'
#      - '_PR_NUMBER=$_PR_NUMBER'
#    waitFor: ['test-e2e']

timeout: 10m

logsBucket: 'gs://$PROJECT_ID-primary-cloudbuild-logs'

tags:
  - 'backend'
  - 'npm'
  - 'nodejs'

secrets:
  - kmsKeyName: projects/production-197117/locations/global/keyRings/gcb/cryptoKeys/main
    secretEnv:
      NPM_TOKEN: 'CiUA/4lqmXwRPPaGHe+X7TS7mwqARNCw5QFq7yfq7ESHaJrf+tzeElEADvOwrLQvnxCLG2wy+H2vD+DWHMosEgIfzpKNBJAVHX1u4FSwIF5utaN6tMIrLuZB18HnK2SKpsXTPvB/+0Eoz1acnj6WO+slz+GUGUnxefU='

options:
  machineType: E2_HIGHCPU_8
