steps:
  - id: lint-yaml
    name: 'us-east1-docker.pkg.dev/$PROJECT_ID/cloudbuilders/yamllint:1.20.0'
    args: ["-d", "relaxed", "."]
    waitFor: ['-']

  - id: lint-docker
    name: 'us-east1-docker.pkg.dev/$PROJECT_ID/cloudbuilders/hadolint:1.18.0'
    args:
      - Dockerfile
    waitFor: ['-']

  - id: npm-lockfile
    name: node:18.12
    secretEnv: ['NPM_TOKEN']
    entrypoint: npm
    args: ['i', '--quiet', '--package-lock-only']

  - id: npm-audit
    name: 'us-east1-docker.pkg.dev/$PROJECT_ID/cloudbuilders/audit-exclude'
    secretEnv: ['NPM_TOKEN']
    entrypoint: '/bin/ash'
    args:
      - -c
      - npm audit --production --json | audit-exclude

  - id: docker-compose
    name: 'gcr.io/cloud-builders/docker'
    args: ['compose', 'up', '-d', '--wait' ]
    waitFor: ['npm-audit', 'lint-yaml', 'lint-docker']

  - id: npm-ci
    name: node:18.12
    secretEnv: ["NPM_TOKEN"]
    entrypoint: npm
    args: [ 'ci', '--quiet']
    waitFor: ['npm-lockfile']

  - id: test-e2e
    name: node:18.12
    secretEnv: ["NPM_TOKEN"]
    entrypoint: npm
    args: ['test']
    env:
      - 'NODE_ENV=test'
      - 'RABBIT_URL=amqp://admin:admin@rabbitmq:5672'
    waitFor: [ 'npm-ci', 'docker-compose' ]

  - id: npm-publish
    name: 'us-east1-docker.pkg.dev/$PROJECT_ID/cloudbuilders/npm:6.13.4'
    secretEnv: ['NPM_TOKEN']
    env:
      - 'TAG_NAME=$TAG_NAME'
      - '_PR_NUMBER=$_PR_NUMBER'
    waitFor: ['test-e2e']

timeout: 10m

logsBucket: 'gs://$PROJECT_ID-primary-cloudbuild-logs'

tags:
  - 'backend'
  - 'npm'
  - 'nodejs'

availableSecrets:
  secretManager:
    - versionName: projects/145393225073/secrets/npm-token-publish/versions/latest
      env: NPM_TOKEN

