jackrabbit:
  image: node@sha256:6e64f63a663a368cc81b28ed3c3e29e6b3784c04f0128be5aaa659157ed4d231
  working_dir: /code
  volumes:
    - .:/code
  links:
    - rabbit
  environment:
    RABBIT_URL: 'amqp://rabbit'
rabbit:
  image: rabbitmq
