version: '3'

services:
  jackrabbit-rpc-server:
    build: .
    environment:
      RABBIT_URL: 'amqp://rabbit'
    entrypoint: ['node', 'examples/7-timeout-rpc/server']
    restart: on-failure
  jackrabbit-rpc-client:
    build: .
    environment:
      RABBIT_URL: 'amqp://rabbit'
    entrypoint: ['node', 'examples/7-timeout-rpc/client']
    restart: on-failure
  rabbit:
    image: rabbitmq:3.10.7-management-alpine@sha256:7c9576f769f1726f7e2cda905fa8e9f1bd0c578146b93e6a3db892ad075e387b
    ports:
      - "5673:5672"
      - "15673:15672"
