version: '3'

services:
  jackrabbit-rpc-server:
    build: .
    environment:
      RABBIT_URL: 'amqp://rabbit'
    entrypoint: ['node', 'examples/7-timeout-rpc/server']
    restart: on-failure
  jackrabbit-rpc-client:
    build: .
    environment:
      RABBIT_URL: 'amqp://rabbit'
    entrypoint: ['node', 'examples/7-timeout-rpc/client']
    restart: on-failure
  rabbit:
    image: rabbitmq:3.8.8-management-alpine@sha256:b0204e3aab819de23ab1f9eb0e1186455f665e032ac3200fc80021fbe773138e
    ports:
      - "5673:5672"
      - "15673:15672"
