version: "3.7"

volumes:
  rabbitmq: {}

services:
  jackrabbit-rpc-server:
    build: .
    environment:
      RABBIT_URL: 'amqp://admin:admin@rabbitmq'
    entrypoint: ['node', 'examples/7-timeout-rpc/server']
    restart: on-failure
  jackrabbit-rpc-client:
    build: .
    environment:
      RABBIT_URL: 'amqp://admin:admin@rabbitmq'
    entrypoint: ['node', 'examples/7-timeout-rpc/client']
    restart: on-failure
  rabbitmq:
    image: rabbitmq:3.10.5-management-alpine@sha256:afceef7d5a4e9b3f5a0bec1e5b78bface72a2ca1a364a5e3918ca7eb453549fa
    restart: unless-stopped
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 30s
      timeout: 30s
      retries: 3
    environment:
      RABBITMQ_DEFAULT_USER: "admin"
      RABBITMQ_DEFAULT_PASS: "${AMQP_PASSWD:-admin}"
    ports:
      - "${AMQP_PORT:-5672}:5672"
      - "${AMQP_MANAGEMENT_PORT:-15672}:15672"
    volumes:
    - "rabbitmq:/var/lib/rabbitmq"

## NOTE: this is a requirement for cloud builds
## If docker-compose is not working for you, simply run
## 'docker network create cloudbuild'
##
networks:
  default:
    name: cloudbuild
    external: true
