version: '3'

services:
  jackrabbit-rpc-server:
    build: .
    environment:
      RABBIT_URL: 'amqp://rabbit'
    entrypoint: ['node', 'examples/7-timeout-rpc/server']
    restart: on-failure
  jackrabbit-rpc-client:
    build: .
    environment:
      RABBIT_URL: 'amqp://rabbit'
    entrypoint: ['node', 'examples/7-timeout-rpc/client']
    restart: on-failure
  rabbit:
    image: rabbitmq:3.8.5-management-alpine@sha256:144b876b5409ef22e90d2f9903339e454738723265c5bfb22e7b10a4696de51a
    ports:
      - "5673:5672"
      - "15673:15672"
