version: '3'

services:
  jackrabbit-rpc-server:
    build: .
    environment:
      RABBIT_URL: 'amqp://rabbit'
    entrypoint: ['node', 'examples/7-timeout-rpc/server']
    restart: on-failure
  jackrabbit-rpc-client:
    build: .
    environment:
      RABBIT_URL: 'amqp://rabbit'
    entrypoint: ['node', 'examples/7-timeout-rpc/client']
    restart: on-failure
  rabbit:
    image: rabbitmq:3.8.9-management-alpine@sha256:82e39fef58778e244bf7692af11b74a734bfb927e535a77c404d89bd2623c8a3
    ports:
      - "5673:5672"
      - "15673:15672"
