version: 2

defaults: &defaults
  working_directory: ~/repo
  docker:
  - image: circleci/node:14.17@sha256:5411d462851417621f569c5af6604076e8e31f74217a428a01254b46167abb60
  - image: rabbitmq:3.8-alpine@sha256:f33b1ca6c2201b413fda7fb95f898524a2f846a75853b1627eec3a8abcde32ab

jobs:
  test:
    <<: *defaults
    environment:
      RABBIT_URL=amqp://localhost
    steps:
    - checkout

    - run:
        name: Audit dependencies
        command: |
          set +e
          set +o pipefail
          if [ -f ".nsprc" ]; then
            sudo npm install --global --quiet audit-filter@0.5;
            npm audit --production --json | audit-filter;
          else
            npm audit --production;
          fi

    - restore_cache:
        keys:
        - v1-dependencies-{{ checksum "package.json" }}
        # fallback to using the latest cache if no exact match is found
        - v1-dependencies-

    - run: npm install
    - run: npm run lint

    - run:
        name: Wait for RabbitMQ to receive connections
        command: dockerize -wait tcp://localhost:5672 -timeout 1m
    - run:
        name: Run tests
        command: npm test

    - save_cache:
        paths:
        - node_modules
        key: v1-dependencies-{{ checksum "package.json" }}

    - persist_to_workspace:
        root: ~/repo
        paths: .

  deploy:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/repo
      - run:
          name: Authenticate with registry
          command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/repo/.npmrc
      - run:
          name: Publish package
          command: npm publish

workflows:
  version: 2
  test-deploy:
    jobs:
      - test:
          filters:
            tags:
              only: /^v.*/
      - deploy:
          requires:
            - test
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
